# Generated by Django 3.0.4 on 2020-04-03 14:11

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=64)),
                ('short_name', models.CharField(default=0, max_length=16)),
                ('polygon', djgeojson.fields.PolygonField(default='{}')),
                ('geom', djgeojson.fields.PointField(default='{}')),
                ('lat', models.CharField(default=0, max_length=30)),
                ('long', models.CharField(default=0, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=64)),
                ('short_name', models.CharField(default=0, max_length=16)),
                ('polygon', djgeojson.fields.PolygonField(default='{}')),
                ('geom', djgeojson.fields.PointField(default='{}')),
                ('lat', models.CharField(default=0, max_length=30)),
                ('long', models.CharField(default=0, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Covid19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('level', models.CharField(default='', max_length=64)),
                ('country_name', models.CharField(default='', max_length=64)),
                ('country_key', models.CharField(default='', max_length=64)),
                ('country_slug', models.SlugField(default='', max_length=64)),
                ('state', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('state_slug', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('county', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('county_slug', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('population', models.PositiveIntegerField(default=0)),
                ('geom', djgeojson.fields.PointField(default='{}')),
                ('polygon', djgeojson.fields.PolygonField(default='{}')),
                ('long', models.CharField(default=0, max_length=30)),
                ('lat', models.CharField(default=0, max_length=30)),
                ('confirmed', models.PositiveIntegerField(default=0)),
                ('deaths', models.PositiveIntegerField(default=0)),
                ('recovered', models.PositiveIntegerField(default=0)),
                ('tested', models.PositiveIntegerField(default=0)),
                ('difference', models.PositiveIntegerField(default=0)),
                ('jsonkey', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=64)),
                ('short_name', models.CharField(default=0, max_length=16)),
                ('polygon', djgeojson.fields.PolygonField(default='{}')),
                ('geom', djgeojson.fields.PointField(default='{}')),
                ('lat', models.CharField(default=0, max_length=30)),
                ('long', models.CharField(default=0, max_length=30)),
            ],
        ),
    ]
