# Generated by Django 3.0.4 on 2020-04-04 19:39

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0002_auto_20200404_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='', max_length=64)),
                ('country', models.CharField(default='', max_length=64)),
                ('state', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('county', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('geom', djgeojson.fields.PointField(default='{}')),
                ('polygon', djgeojson.fields.PolygonField(default='{}')),
                ('long', models.CharField(default=0, max_length=30)),
                ('lat', models.CharField(default=0, max_length=30)),
            ],
        ),
    ]
