# Generated by Django 3.0.4 on 2020-04-04 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0003_borders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borders',
            name='geom',
        ),
    ]
