# Generated by Django 3.0.4 on 2020-04-04 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0004_remove_borders_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borders',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='borders',
            name='long',
        ),
    ]
