# Generated by Django 3.0.3 on 2020-03-24 20:56

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coronamap', '0002_covid19info'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid19info',
            name='active',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='covid19info',
            name='combinedKey',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='covid19info',
            name='geom',
            field=djgeojson.fields.PointField(default='{}'),
        ),
        migrations.AddField(
            model_name='covid19info',
            name='lat',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='covid19info',
            name='long',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='covid19info',
            name='province',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='covid19info',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
    ]
