# Generated by Django 3.0.3 on 2020-03-27 09:57

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coronamap', '0003_auto_20200324_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid19InfoByCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('country', models.CharField(default='', max_length=50)),
                ('date', models.DateField(null=True)),
                ('lat', models.CharField(default=0, max_length=30)),
                ('long', models.CharField(default=0, max_length=30)),
                ('confirmed', models.PositiveIntegerField(default=0)),
                ('deaths', models.PositiveIntegerField(default=0)),
                ('recovered', models.PositiveIntegerField(default=0)),
                ('active', models.PositiveIntegerField(default=0)),
                ('combinedKey', models.CharField(max_length=50, null=True)),
                ('geom', djgeojson.fields.PointField(default='{}')),
            ],
        ),
        migrations.DeleteModel(
            name='MushroomSpot',
        ),
    ]
