# Generated by Django 3.0.3 on 2020-03-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coronamap', '0004_auto_20200327_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid19infobycountry',
            name='difference',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
